const fs = require('fs');
let code = fs.readFileSync('src/data/tmdbData.ts', 'utf8');

const oldIncredibles = `  // THE INCREDIBLES
  {
    id: 'tmdb-movie-9806',
    tmdbId: 9806,
    title: 'The Incredibles',
    name: 'The Incredibles',
    original_title: 'The Incredibles',
    poster_path: null,
    posterUrl: 'https://static.tvmaze.com/uploads/images/original_untouched/12/30048.jpg',
    resolvedPosterUrl: 'https://static.tvmaze.com/uploads/images/original_untouched/12/30048.jpg',
    backdrop_path: null,
    backdropUrl: 'https://static.tvmaze.com/uploads/images/original_untouched/12/30048.jpg',
    overview: 'Bob Parr (Mr. Incredible) and his wife Helen (Elastigirl) are forced to live normal suburban lives with their children until a mysterious assignment calls Bob back into action.',
    vote_average: 8.4,
    vote_count: 17200,
    release_date: '2004-11-05',
    genres: ['Animation', 'Action', 'Adventure', 'Family', 'Superhero'],
    genre_ids: [16, 28, 12, 10751],
    media_type: 'movie',
    navType: 'Movies',
    category: 'Cause You Like',
    durationMinutes: 115,
    totalEpisodes: 1,
    seasonCount: 1,
    studio: 'Pixar Animation Studios / Brad Bird',
    qualityBadges: ['4K REMASTER', 'MICHAEL GIACCHINO JAZZ', 'ATMOS'],
    matchScore: 98,
    tagline: 'Twice the fight. Superheroes reunited.'
  },`;

const newIncredibles = `  // THE INCREDIBLES
  {
    id: 'tmdb-movie-9806',
    tmdbId: 9806,
    title: 'The Incredibles',
    name: 'The Incredibles',
    original_title: 'The Incredibles',
    poster_path: null,
    posterUrl: 'https://media.themoviedb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg',
    resolvedPosterUrl: 'https://media.themoviedb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg',
    backdrop_path: null,
    backdropUrl: 'https://media.themoviedb.org/t/p/original/lxwzY9vNwjDgxWKt3zZ6zcU6rEJ.jpg',
    overview: 'Bob Parr (Mr. Incredible) and his wife Helen (Elastigirl) are forced to live normal suburban lives with their children until a mysterious assignment calls Bob back into action.',
    vote_average: 8.4,
    vote_count: 17200,
    release_date: '2004-11-05',
    genres: ['Animation', 'Action', 'Adventure', 'Family', 'Superhero'],
    genre_ids: [16, 28, 12, 10751],
    media_type: 'movie',
    navType: 'Movies',
    category: 'Cause You Like',
    durationMinutes: 115,
    totalEpisodes: 1,
    seasonCount: 1,
    studio: 'Pixar Animation Studios / Brad Bird',
    qualityBadges: ['4K REMASTER', 'MICHAEL GIACCHINO JAZZ', 'ATMOS'],
    matchScore: 98,
    tagline: 'Twice the fight. Superheroes reunited.'
  },
  // INCREDIBLES 2
  {
    id: 'tmdb-movie-260513',
    tmdbId: 260513,
    title: 'Incredibles 2',
    name: 'Incredibles 2',
    original_title: 'Incredibles 2',
    poster_path: null,
    posterUrl: 'https://media.themoviedb.org/t/p/w500/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg',
    resolvedPosterUrl: 'https://media.themoviedb.org/t/p/w500/9lFKBtaVIhP7E2Pk0IY1CwTKTMZ.jpg',
    backdrop_path: null,
    backdropUrl: 'https://media.themoviedb.org/t/p/original/mabuNsGJgRuCTuGqjFkWe1xdu19.jpg',
    overview: 'Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.',
    vote_average: 7.5,
    vote_count: 12400,
    release_date: '2018-06-14',
    genres: ['Animation', 'Action', 'Adventure', 'Family', 'Superhero'],
    genre_ids: [16, 28, 12, 10751],
    media_type: 'movie',
    navType: 'Movies',
    category: 'Cause You Like',
    durationMinutes: 118,
    totalEpisodes: 1,
    seasonCount: 1,
    studio: 'Pixar Animation Studios / Brad Bird',
    qualityBadges: ['4K ULTRA HD', 'ATMOS'],
    matchScore: 95,
    tagline: 'Back to work.'
  },
  // INCREDIBLES 3
  {
    id: 'tmdb-movie-1327821',
    tmdbId: 1327821,
    title: 'Incredibles 3',
    name: 'Incredibles 3',
    original_title: 'Incredibles 3',
    poster_path: null,
    posterUrl: 'https://media.themoviedb.org/t/p/w500/por0sU3WKbboM2e1M6oGlPFAEiF.jpg',
    resolvedPosterUrl: 'https://media.themoviedb.org/t/p/w500/por0sU3WKbboM2e1M6oGlPFAEiF.jpg',
    backdrop_path: null,
    backdropUrl: 'https://media.themoviedb.org/t/p/original/por0sU3WKbboM2e1M6oGlPFAEiF.jpg',
    overview: 'The Parr family returns for another adventure. Currently in development at Pixar Animation Studios.',
    vote_average: 0.0,
    vote_count: 0,
    release_date: 'TBA',
    genres: ['Animation', 'Action', 'Adventure', 'Family', 'Superhero'],
    genre_ids: [16, 28, 12, 10751],
    media_type: 'movie',
    navType: 'Movies',
    category: 'Explore More',
    durationMinutes: 0,
    totalEpisodes: 1,
    seasonCount: 1,
    studio: 'Pixar Animation Studios / Brad Bird',
    qualityBadges: ['IN PRODUCTION'],
    matchScore: 99,
    tagline: 'The next chapter.'
  },`;

code = code.replace(oldIncredibles, newIncredibles);
fs.writeFileSync('src/data/tmdbData.ts', code, 'utf8');
