import { GlobalAgentPlan } from './globalRepositoryAgent';

export interface SupervisorReview {
  approved: boolean;
  score: number; // 0 to 100
  critique: string;
  flaggedIssues: string[];
}

export class AiSupervisor {
  private static OLLAMA_URL = 'http://localhost:11434/api/generate';
  private static GEMINI_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent';

  /**
   * Reviews the proposed patch plan generated by the main AI agents
   */
  public static async reviewBotOutput(
    originalAudit: Record<string, any>,
    proposedPlan: GlobalAgentPlan
  ): Promise<SupervisorReview> {
    console.log('🛡️ [AI Supervisor] Inspecting proposed patch plan from main AI agents...');

    // 1. Fast Structural Safety Checks (Local Rules)
    const localCheck = this.runLocalSafetyRules(proposedPlan);
    if (!localCheck.approved) {
      console.warn('⚠️ [AI Supervisor Blocked] Failed structural safety rules:', localCheck.critique);
      return localCheck;
    }

    // 2. High-Reasoning AI Review (Passes plan to Supervisor Model)
    const prompt = this.constructSupervisorPrompt(originalAudit, proposedPlan);
    const review = await this.querySupervisorModel(prompt);

    if (review.approved) {
      console.log(`✅ [AI Supervisor Approved] Score: ${review.score}/100. Safe to deploy patches!`);
    } else {
      console.warn(`🚨 [AI Supervisor Rejected] Score: ${review.score}/100. Reason: ${review.critique}`);
    }

    return review;
  }

  /**
   * Rule-Based Checks: Catches obvious hallucinations, missing code, or styling violations instantly
   */
  private static runLocalSafetyRules(plan: GlobalAgentPlan): SupervisorReview {
    const flagged: string[] = [];

    plan.patches.forEach((patch) => {
      // Check for lazy AI placeholders
      if (
        patch.updatedContent.includes('// TODO') ||
        patch.updatedContent.includes('// Rest of code here') ||
        patch.updatedContent.includes('/* ... */')
      ) {
        flagged.push(`Lazy placeholder detected in ${patch.filePath}`);
      }

      // Check for theme consistency
      if (patch.filePath.endsWith('.tsx') && !patch.updatedContent.includes('bg-[#07151e]')) {
        flagged.push(`App background theme color missing in ${patch.filePath}`);
      }
    });

    if (flagged.length > 0) {
      return {
        approved: false,
        score: 30,
        critique: 'Bot output contained lazy code placeholders or broke UI theme rules.',
        flaggedIssues: flagged,
      };
    }

    return { approved: true, score: 100, critique: 'Passed local safety checks.', flaggedIssues: [] };
  }

  /**
   * Constructs strict audit prompt for the Supervisor AI
   */
  private static constructSupervisorPrompt(audit: Record<string, any>, plan: GlobalAgentPlan): string {
    return `
System Role: You are the Chief AI Inspector and Lead Security Auditor.
Your Job: Audit the proposed code patches generated by an AI assistant to fix a software bug.

Original Audit Bug Report:
\`\`\`json
${JSON.stringify(audit, null, 2)}
\`\`\`

Proposed Agent Plan & Patches:
\`\`\`json
${JSON.stringify(plan, null, 2)}
\`\`\`

Instructions:
Evaluate if the proposed patches correctly resolve the bug without breaking existing imports, syntax, or security.
Return ONLY valid JSON:
{
  "approved": true | false,
  "score": 95,
  "critique": "Explanation of verdict",
  "flaggedIssues": ["Issue 1", "Issue 2"]
}
`.trim();
  }

  private static async querySupervisorModel(prompt: string): Promise<SupervisorReview> {
    try {
      const meta = import.meta as any;
      const geminiKey = (typeof import.meta !== 'undefined' && meta?.env?.VITE_GEMINI_API_KEY) || '';
      if (geminiKey) {
        const res = await fetch(`${this.GEMINI_URL}?key=${geminiKey}`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: { responseMimeType: 'application/json' },
          }),
        });

        if (res.ok) {
          const data = await res.json();
          const parsed = JSON.parse(data.candidates[0].content.parts[0].text);
          return parsed;
        }
      }
    } catch {
      // Fallback if network fails
    }

    return {
      approved: false,
      score: 0,
      critique: 'Supervisor review network check failed. Defaulting to safe reject.',
      flaggedIssues: ['Supervisor offline'],
    };
  }
}
