// src/utils/syntaxSanitizerAgent.ts

export interface SanitizerConfig {
  useSingleQuotes?: boolean;
  tabWidth?: number;
  normalizeMotionProps?: boolean;
  stripMarkdownFences?: boolean;
}

export class SyntaxSanitizerAgent {
  private static defaultConfig: SanitizerConfig = {
    useSingleQuotes: true,
    tabWidth: 2,
    normalizeMotionProps: true,
    stripMarkdownFences: true,
  };

  /**
   * Sanitizes, formats, and normalizes raw code snippets generated by AI models or builders.
   */
  public static sanitizeCode(
    rawCode: string,
    config: SanitizerConfig = {}
  ): string {
    if (!rawCode) return '';

    const opts = { ...this.defaultConfig, ...config };
    let sanitized = rawCode;

    // 1. Strip Markdown Code Fences (```tsx, ```json, etc.)
    if (opts.stripMarkdownFences) {
      sanitized = sanitized.replace(/^```[a-zA-Z]*\n?/gm, '').replace(/```$/gm, '').trim();
    }

    // 2. Normalize Tab Indentation (Replace tabs or irregular spaces with strict 2-space increments)
    if (opts.tabWidth) {
      const indent = ' '.repeat(opts.tabWidth);
      sanitized = sanitized.replace(/\t/g, indent);
    }

    // 3. Normalize Framer Motion / Motion JSX Props
    if (opts.normalizeMotionProps) {
      // Standardize double quotes to single quotes in transition specs
      sanitized = sanitized.replace(
        /transition=\{\{\s*type:\s*["']spring["'],\s*damping:\s*(\d+),\s*stiffness:\s*(\d+)\s*\}\}/g,
        "transition={{ type: 'spring', damping: $1, stiffness: $2 }}"
      );
      sanitized = sanitized.replace(/type="spring"/g, "type='spring'");
      sanitized = sanitized.replace(/type="tween"/g, "type='tween'");
    }

    // 4. Convert Double-Quoted String Props to Single Quotes in JSX
    if (opts.useSingleQuotes) {
      // Replaces className="..." with className='...' safely for standard JSX string attributes
      sanitized = sanitized.replace(/([a-zA-Z0-9_-]+)="([^"\n]+)"/g, "$1='$2'");
    }

    return sanitized.trim();
  }

  /**
   * Fast targeted sanitizer specifically for JSON payload strings from Gemini/Ollama
   */
  public static sanitizeJsonString(rawJson: string): string {
    if (!rawJson) return '{}';
    let clean = rawJson.replace(/^```json\n?/gm, '').replace(/^```\n?/gm, '').replace(/```$/gm, '').trim();
    
    // Fix trailing commas before closing braces/brackets
    clean = clean.replace(/,\s*([}\]])/g, '$1');
    return clean;
  }

  /**
   * Legacy adapter for backward compatibility with AIDevEngine
   */
  public static sanitizeJsxProps(rawCode: string): string {
    return this.sanitizeCode(rawCode);
  }
}
